### PR TITLE
rk3308: ddr: add uart0 loader

### PR DESCRIPTION
**Pull request by angeloc**
Adding uart0 loader for boards with serial console on uart0 (Rock Pi s)

In the process of adding a Rock Pi S in buildroot, I noticed that i cannot run an x86 binary on the host because buildroot use host tools built from sources.
Therefore I need to have the loader for uart0 already available as binary.

Signed-off-by: Angelo Compagnucci <angelo@amarulasolutions.com>

### CODE REVIEW

**Comment by angeloc** [comment]
@derrick-huang @ZhengShunQian any news?

**Comment by angeloc** [comment]
@JosephChen2017 updated to v2.07

**Comment by scottgoldenpro** [comment]
It doesn't have 86 force 64 py. 64--120 default is it tapped is the other chip

**Comment by obbardc** [comment]
@angeloc how did you build this out of interest ?

**Comment by Yaksinikos** [comment]
I hve found a "RK30xxLoader(L)_V2.19.bin" on the net as well, would be nice to see it in the official repository, as well as a updated tools folder, at least rkdeveloptool, rkflashtool are out of date.

**Comment by angeloc** [comment]
Nobody is interested, closing this PR

**Comment by obbardc** [comment]
@angeloc Can you explain what you did to build the binary, in case others are interested in future?

**Comment by angeloc** [comment]
@obbardc There is documentation about using the tools to change parameters here https://github.com/rockchip-linux/rkbin/blob/master/tools/ddrbin_tool_user_guide.txt

**Pull request closed without merging**
